apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-demo
  labels:
    app: mlops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-demo
  template:
    metadata:
      labels:
        app: mlops-demo
    spec:
      containers:
      - name: mlops-demo
        image: growwithtech/mlops-demo:17
        ports:
        - containerPort: 5000
        env:
        - name: ENV_VAR_NAME
          value: "your-env-var-value"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: mlops-demo-config
