name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      env:
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        echo "Build Number: $IMAGE_TAG"
        docker build -t growwithtech/mlops-demo:$IMAGE_TAG ./mlops-demo/src
        docker tag growwithtech/mlops-demo:$IMAGE_TAG growwithtech/mlops-demo:latest
        docker push growwithtech/mlops-demo:$IMAGE_TAG
        docker push growwithtech/mlops-demo:latest

    - name: Update Kubernetes Manifest
      run: |
        sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:$IMAGE_TAG|g" ./mlops-demo/k8s/deployment.yaml
        echo "Updated image tag in manifest to $IMAGE_TAG"
    
    - name: Commit Updated Manifest
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add ./mlops-demo/k8s/deployment.yaml
        git commit -m "Update image tag to $IMAGE_TAG [ci skip]" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.MANIFEST_UPDATER_TOKEN }} # or use PERSONAL_TOKEN if pushing to a different repo

