name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      env:
        IMAGE_TAG: ${{ github.run_number }}
      run: |
        echo "Build Number: $IMAGE_TAG"
        docker build -t growwithtech/mlops-demo:$IMAGE_TAG ./mlops-demo/src
        docker tag growwithtech/mlops-demo:$IMAGE_TAG growwithtech/mlops-demo:latest
        docker push growwithtech/mlops-demo:$IMAGE_TAG
        docker push growwithtech/mlops-demo:latest

    - name: Update Kubernetes Manifest
      run: |
        sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:$IMAGE_TAG|g" ./mlops-demo/kubernetes/deployment.yaml
        echo "Updated image tag in manifest to $IMAGE_TAG"
    
    - name: Commit Updated Manifest
      env:
        TOKEN: ${{ secrets.MANIFEST_UPDATER_TOKEN }} # Must be a PAT with repo access
      run: |
        pwd
        ls -ltr */*
        git config user.name "growwithtech01"
        git config user.email "growwithtechzone@gmail.com"

        # Authenticate using the token
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/growwithtech01/mlops-101

        git add ./mlops-demo/kubernetes/deployment.yaml
        git commit -m "Update image tag to $IMAGE_TAG [ci skip]" || echo "No changes to commit"
        git push origin main

